swagger: "2.0"
info:
  version: "0.0.1"
  title: Trend musix
host: localhost:10010
basePath: /
#
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /track/get-track:
    x-swagger-router-controller: track
    get:
      description: Get track's data
      operationId: getTrack
      parameters:
        - name: token
          in: query
          description: User's token
          required: true
          type: string
        - name: id
          in: query
          description: Track's id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/TrackResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /test:
    x-swagger-router-controller: user
    get:
      description: Get existence of value
      operationId: test
      parameters:
        - name: key
          in: query
          description: Token
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Response"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Response"
  /user/signup:
    x-swagger-router-controller: user
    post:
      description: Sign up
      operationId: signup
      parameters:
        - name: user_info_signup
          in: body
          description: User info sign up
          required: true
          schema:
            $ref: "#/definitions/UserInfoSignUp"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        "400":
          description: Error
          schema:
            $ref: "#/definitions/Response"
  /user/login:
    x-swagger-router-controller: user
    post:
      description: Login and get token for user
      operationId: login
      parameters:
        - name: user_info
          in: body
          description: User info
          required: true
          schema:
            $ref: "#/definitions/UserInfo"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        "400":
          description: Error
          schema:
            $ref: "#/definitions/Response"
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  TrackInfoResponse:
    properties:
      id:
        type: string
      title:
        type: string
      artist:
        type: string
      artist_imageurl:
        type: string
      genre:
        type: string
      genre_imageurl:
        type: string
      imageurl:
        type: string
      url:
        type: string
      like:
        type: number
      listen:
        type: number
  TrackFeatureResponse:
    properties:
      speechiness:
        type: number
      acousticness:
        type: number
      instrumentalness:
        type: number
      liveness:
        type: number
      valence:
        type: number
      duration_ms:
        type: number
      tempo:
        type: number
      time_signature:
        type: number
      mode:
        type: number
      key:
        type: number
      loudness:
        type: number
      danceability:
        type: number
      energy:
        type: number
  TrackResponse:
    properties:
      info:
        type: object
        $ref: "#/definitions/TrackInfoResponse"
      lyric:
        type: string
      feature:
        type: object
        $ref: "#/definitions/TrackFeatureResponse"
      hit:
        type: boolean
  UserResponse:
    properties:
      username:
        type: string
      fullname:
        type: string
      expire:
        type: number
      token:
        type: string
  UserInfoSignUp:
    properties:
      username:
        type: string
      fullname:
        type: string
      password:
        type: string 
  UserInfo:
    properties:
      username:
        type: string
      password:
        type: string
  Response:
    properties:
      status:
        type: integer
      message:
        type: string
  
