swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
host: localhost:10010
basePath: /
#
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /track/get-track:
    x-swagger-router-controller: track
    get:
      description: Returns 'Hello' to the caller\
      operationId: getTrack
      parameters:
        - name: token
          in: query
          description: User's token
          required: true
          type: string
        - name: id
          in: query
          description: Track's id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/TrackResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  TrackInfoResponse:
    properties:
      id:
        type: string
      title:
        type: string
      artist:
        type: string
      artist_imageurl:
        type: string
      genre:
        type: string
      genre_imageurl:
        type: string
      imageurl:
        type: string
      url:
        type: string
      like:
        type: number
      listen:
        type: number
  TrackFeatureResponse:
    properties:
      speechiness:
        type: number
      acousticness:
        type: number
      instrumentalness:
        type: number
      liveness:
        type: number
      valence:
        type: number
      duration_ms:
        type: number
      tempo:
        type: number
      time_signature:
        type: number
      mode:
        type: number
      key:
        type: number
      loudness:
        type: number
      danceability:
        type: number
      energy:
        type: number
  TrackResponse:
    properties:
      info:
        type: object
        $ref: "#/definitions/TrackInfoResponse"
      lyric:
        type: string
      feature:
        type: object
        $ref: "#/definitions/TrackFeatureResponse"
      hit:
        type: boolean
