swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
  /test:
    x-swagger-router-controller: user
    get:
      description: Get existence of value
      operationId: test
      parameters:
        - name: key
          in: query
          description: Token
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Response"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Response"
  /user/signup:
    x-swagger-router-controller: user
    post:
      description: Sign up
      operationId: signup
      parameters:
        - name: user_info_signup
          in: body
          description: User info sign up
          required: true
          schema:
            $ref: "#/definitions/UserInfoSignUp"

      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        "400":
          description: Error
          schema:
            $ref: "#/definitions/Response"
  /user/login:
    x-swagger-router-controller: user
    post:
      description: Login and get token for user
      operationId: login
      parameters:
        - name: user_info
          in: body
          description: User info
          required: true
          schema:
            $ref: "#/definitions/UserInfo"

      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        "400":
          description: Error
          schema:
            $ref: "#/definitions/Response"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  UserResponse:
    properties:
      username:
        type: string
      fullname:
        type: string
      expire:
        type: number
      token:
        type: string
  UserInfoSignUp:
    properties:
      username:
        type: string
      fullname:
        type: string
      password:
        type: string 
  UserInfo:
    properties:
      username:
        type: string
      password:
        type: string
  Response:
    properties:
      status:
        type: integer
      message:
        type: string
  
